version: '3.8'

services:
    dev:
        image: idle-trading-hero-frontend:latest
        environment:
            - VUE_APP_BACKEND_URL
        build:
            context: ./
            target: dev
        ports:
            - '8080:8080'
        volumes:
            - ./:/app
            - /app/node_modules
